#pragma once
#undef max

#include "SDK.hpp"
#include <iostream>

using namespace SDK;

namespace ItemSpawner
{
    inline const std::unordered_map<int, TSubclassOf<AActor>> ItemMap = {
        { 1, ABP_Armor_Arms_Chains_T1_C::StaticClass() },
        { 2, ABP_Armor_Arms_Chains_T2_C::StaticClass() },
        { 3, ABP_Armor_Arms_Vambrace_A_T2_C::StaticClass() },
        { 4, ABP_Armor_Arms_Vambrace_A_T3_C::StaticClass() },
        { 5, ABP_Armor_Arms_Vambrace_B_T2_C::StaticClass() },
        { 6, ABP_Armor_Arms_Vambrace_B_T3_C::StaticClass() },
        { 7, ABP_Armor_Arms_Vambrace_C_T2_C::StaticClass() },
        { 8, ABP_Armor_Arms_Vambrace_C_T3_B_C::StaticClass() },
        { 9, ABP_Armor_Arms_Vambrace_C_T3_C::StaticClass() },
        { 10, ABP_Armor_Body_Brestplate_A_T1_C::StaticClass() },
        { 11, ABP_Armor_Body_Brestplate_A_T2_C::StaticClass() },
        { 12, ABP_Armor_Body_Brestplate_B_T1_C::StaticClass() },
        { 13, ABP_Armor_Body_Brestplate_B_T2_C::StaticClass() },
        { 14, ABP_Armor_Body_Cuirass_A_T2_C::StaticClass() },
        { 15, ABP_Armor_Body_Cuirass_B_T1_C::StaticClass() },
        { 16, ABP_Armor_Body_Cuirass_C_T1_C::StaticClass() },
        { 17, ABP_Armor_Body_Cuirass_C_T2_C::StaticClass() },
        { 18, ABP_Armor_Body_Cuirass_C_T3_B_C::StaticClass() },
        { 19, ABP_Armor_Body_Cuirass_C_T3_C::StaticClass() },
        { 20, ABP_Armor_Body_Doublet_Arming_C::StaticClass() },
        { 21, ABP_Armor_Body_Doublet_C::StaticClass() },
        { 22, ABP_Armor_Body_Gambeson_A_T1_C::StaticClass() },
        { 23, ABP_Armor_Body_Gambeson_A_T2_C::StaticClass() },
        { 24, ABP_Armor_Body_Gambeson_B_T1_C::StaticClass() },
        { 25, ABP_Armor_Body_Gambeson_B_T2_C::StaticClass() },
        { 26, ABP_Armor_Body_Plackard_T2_C::StaticClass() },
        { 27, ABP_Armor_Body_Shirt_A_C::StaticClass() },
        { 28, ABP_Armor_Body_Shirt_B_C::StaticClass() },
        { 29, ABP_Armor_Feet_Sabbatons_AB_C::StaticClass() },
        { 30, ABP_Armor_Feet_Sabbatons_A_C::StaticClass() },
        { 31, ABP_Armor_Feet_Shoes_A_C::StaticClass() },
        { 32, ABP_Armor_Feet_Shoes_B_C::StaticClass() },
        { 33, ABP_Armor_Feet_Shoes_C_C::StaticClass() },
        { 34, ABP_Armor_Hands_Gauntlets_T1_C::StaticClass() },
        { 35, ABP_Armor_Hands_Gauntlets_T2_C::StaticClass() },
        { 36, ABP_Armor_Hands_Gauntlets_T3B_C::StaticClass() },
        { 37, ABP_Armor_Hands_Gauntlets_T3_C::StaticClass() },
        { 38, ABP_Armor_Hands_HalfGauntlets_T1_C::StaticClass() },
        { 39, ABP_Armor_Hands_HalfGauntlets_T2_C::StaticClass() },
        { 40, ABP_Armor_Head_Armet_001_B_C::StaticClass() },
        { 41, ABP_Armor_Head_Armet_001_C::StaticClass() },
        { 42, ABP_Armor_Head_Armet_001_R_C::StaticClass() },
        { 43, ABP_Armor_Head_Barbute_A_C::StaticClass() },
        { 44, ABP_Armor_Head_Barbute_B_C::StaticClass() },
        { 45, ABP_Armor_Head_Hat_Bycocket_A_001_C::StaticClass() },
        { 46, ABP_Armor_Head_Hat_Bycocket_A_002_C::StaticClass() },
        { 47, ABP_Armor_Head_Hat_Bycocket_B_001_C::StaticClass() },
        { 48, ABP_Armor_Head_Hat_Bycocket_B_002_C::StaticClass() },
        { 49, ABP_Armor_Head_Hat_Bycocket_C_001_C::StaticClass() },
        { 50, ABP_Armor_Head_Hat_Bycocket_D_001_C::StaticClass() },
        { 51, ABP_Armor_Head_Hat_Bycocket_E_001_C::StaticClass() },
        { 52, ABP_Armor_Head_Hat_Bycocket_F_001_C::StaticClass() },
        { 53, ABP_Armor_Head_Hat_Bycocket_G_001_C::StaticClass() },
        { 54, ABP_Armor_Head_Hat_Bycocket_H_001_C::StaticClass() },
        { 55, ABP_Armor_Head_Hat_Bycocket_I_001_C::StaticClass() },
        { 56, ABP_Armor_Head_Hat_Bycocket_J_001_C::StaticClass() },
        { 57, ABP_Armor_Head_Hat_Gnome_A_C::StaticClass() },
        { 58, ABP_Armor_Head_Hat_Gnome_B_C::StaticClass() },
        { 59, ABP_Armor_Head_Kettle_Helm_A_C::StaticClass() },
        { 60, ABP_Armor_Head_Kettle_Helm_B_C::StaticClass() },
        { 61, ABP_Armor_Head_Kettle_Helm_C_C::StaticClass() },
        { 62, ABP_Armor_Head_Kettle_Helm_D_C::StaticClass() },
        { 63, ABP_Armor_Head_Sallet_Open_A_001_C::StaticClass() },
        { 64, ABP_Armor_Head_Sallet_Open_B_001_C::StaticClass() },
        { 65, ABP_Armor_Head_Sallet_Open_CA_001_C::StaticClass() },
        { 66, ABP_Armor_Head_Sallet_Open_CB_001_C::StaticClass() },
        { 67, ABP_Armor_Head_Sallet_Solid_A_001_C::StaticClass() },
        { 68, ABP_Armor_Head_Sallet_Solid_A_002_C::StaticClass() },
        { 69, ABP_Armor_Head_Sallet_Solid_B_001_C::StaticClass() },
        { 70, ABP_Armor_Head_Sallet_Solid_B_002_C::StaticClass() },
        { 71, ABP_Armor_Head_Sallet_Solid_C_001_C::StaticClass() },
        { 72, ABP_Armor_Head_Sallet_Solid_C_002_C::StaticClass() },
        { 73, ABP_Armor_Head_Sallet_Solid_D_001_C::StaticClass() },
        { 74, ABP_Armor_Head_Sallet_Solid_D_002_C::StaticClass() },
        { 75, ABP_Armor_Head_Sallet_Solid_E_001_C::StaticClass() },
        { 76, ABP_Armor_Head_Sallet_Solid_E_002_C::StaticClass() },
        { 77, ABP_Armor_Head_Sallet_Visor_A_001_C::StaticClass() },
        { 78, ABP_Armor_Head_Sallet_Visor_B_001_C::StaticClass() },
        { 79, ABP_Armor_Legs_Cuisse_A_T2_C::StaticClass() },
        { 80, ABP_Armor_Legs_Cuisse_A_T3_C::StaticClass() },
        { 81, ABP_Armor_Legs_Cuisse_B_C::StaticClass() },
        { 82, ABP_Armor_Legs_Greaves_T2_C::StaticClass() },
        { 83, ABP_Armor_Legs_Greaves_T3_C::StaticClass() },
        { 84, ABP_Armor_Legs_Hosen_Arming_A_C::StaticClass() },
        { 85, ABP_Armor_Legs_Hosen_A_C::StaticClass() },
        { 86, ABP_Armor_Legs_Hosen_B_C::StaticClass() },
        { 87, ABP_Armor_Legs_Hosen_C_C::StaticClass() },
        { 88, ABP_Armor_Legs_Panties_C::StaticClass() },
        { 89, ABP_Armor_Neck_Bevor_T2_C::StaticClass() },
        { 90, ABP_Armor_Neck_Bevor_T3_C::StaticClass() },
        { 91, ABP_Armor_Neck_Standard_T1_C::StaticClass() },
        { 92, ABP_Armor_Neck_Standard_T2_C::StaticClass() },
        { 93, ABP_Armor_Neck_Standard_T3_C::StaticClass() },
        { 94, ABP_Armor_Shoulders_Pauldron_C_B_C::StaticClass() },
        { 95, ABP_Armor_Shoulders_Pauldron_C_C::StaticClass() },
        { 96, ABP_Armor_Shoulders_Spaulder_A_T2_C::StaticClass() },
        { 97, ABP_Armor_Shoulders_Spaulder_A_T3_C::StaticClass() },
        { 98, ABP_Armor_Shoulders_Spaulder_B_T2_C::StaticClass() },
        { 99, ABP_Armor_Shoulders_Spaulder_B_T3_C::StaticClass() },
        { 100, ABP_Armor_Waist_Foulds_T1_C::StaticClass() },
        { 101, ABP_Armor_Waist_Foulds_T2_C::StaticClass() },
        { 102, ABP_Armor_Waist_Foulds_T3_C::StaticClass() },
        { 103, ABP_Weapon_Improv_CandleStick_Big_C::StaticClass() },
        { 104, ABP_Weapon_Improv_CandleStick_Small_C::StaticClass() },
        { 105, ABP_Weapon_Improv_Stool_C::StaticClass() },
        { 106, ABP_Weapon_Tool_Axe_A_C::StaticClass() },
        { 107, ABP_Weapon_Tool_Axe_B_C::StaticClass() },
        { 108, ABP_Weapon_Tool_Axe_C_C::StaticClass() },
        { 109, ABP_Weapon_Tool_Hammer_A_C::StaticClass() },
        { 110, ABP_Weapon_Tool_Hammer_B_C::StaticClass() },
        { 111, ABP_Weapon_Tool_Hammer_C_C::StaticClass() },
        { 112, ABP_Weapon_Tool_Hoe_A_C::StaticClass() },
        { 113, ABP_Weapon_Tool_Knife_A_C::StaticClass() },
        { 114, ABP_Weapon_Tool_Knife_B_C::StaticClass() },
        { 115, ABP_Weapon_Tool_Knife_C_C::StaticClass() },
        { 116, ABP_Weapon_Tool_Pitchfork_A_C::StaticClass() },
        { 117, ABP_Weapon_Tool_Scissors_C::StaticClass() },
        { 118, ABP_Weapon_Tool_Shovel_A_C::StaticClass() },
        { 119, ABP_Weapon_Tool_Shovel_B_C::StaticClass() },
        { 120, ABP_Weapon_Tool_Sickle_A_C::StaticClass() },
        { 121, ABP_Weapon_Tool_Sickle_D_C::StaticClass() },
        { 122, ABP_Weapon_Tool_Sickle_E_C::StaticClass() },
        { 123, ABP_Weapon_Tool_Tongs_C::StaticClass() },
        { 124, AModularWeaponBP_ArmingSword_C::StaticClass() },
        { 125, AModularWeaponBP_ArmingSword_T1_C::StaticClass() },
        { 126, AModularWeaponBP_ArmingSword_T2_C::StaticClass() },
        { 127, AModularWeaponBP_ArmingSword_T3_C::StaticClass() },
        { 128, AModularWeaponBP_Axe2H_C::StaticClass() },
        { 129, AModularWeaponBP_Axe_C::StaticClass() },
        { 130, AModularWeaponBP_BastardSword_T1_C::StaticClass() },
        { 131, AModularWeaponBP_BastardSword_T2_C::StaticClass() },
        { 132, AModularWeaponBP_BastardSword_T3_C::StaticClass() },
        { 133, AModularWeaponBP_Billhook_A_C::StaticClass() },
        { 134, AModularWeaponBP_Billhook_B_C::StaticClass() },
        { 135, AModularWeaponBP_C::StaticClass() },
        { 136, AModularWeaponBP_Dagger_C::StaticClass() },
        { 137, AModularWeaponBP_Dagger_T1_C::StaticClass() },
        { 138, AModularWeaponBP_Dagger_T2_C::StaticClass() },
        { 139, AModularWeaponBP_Falchion_Long_C::StaticClass() },
        { 140, AModularWeaponBP_Falchion_Long_T1_C::StaticClass() },
        { 141, AModularWeaponBP_Falchion_Long_T2_C::StaticClass() },
        { 142, AModularWeaponBP_Falchion_Short_C::StaticClass() },
        { 143, AModularWeaponBP_Falchion_Short_T1_C::StaticClass() },
        { 144, AModularWeaponBP_Falchion_Short_T2_C::StaticClass() },
        { 145, AModularWeaponBP_GreatSword_C::StaticClass() },
        { 146, AModularWeaponBP_Hafted_High_Tier_Short_C::StaticClass() },
        { 147, AModularWeaponBP_Hafted_Low_Tier_Short_C::StaticClass() },
        { 148, AModularWeaponBP_Hafted_Mid_Tier_Avg_C::StaticClass() },
        { 149, AModularWeaponBP_Hafted_Mid_Tier_Long_C::StaticClass() },
        { 150, AModularWeaponBP_Hafted_Mid_Tier_Short_C::StaticClass() },
        { 151, AModularWeaponBP_Halberd_A_C::StaticClass() },
        { 152, AModularWeaponBP_Halberd_B_C::StaticClass() },
        { 153, AModularWeaponBP_LongSword_T2_C::StaticClass() },
        { 154, AModularWeaponBP_LongSword_T3_C::StaticClass() },
        { 155, AModularWeaponBP_Mace_High_Tier_Avg_C::StaticClass() },
        { 156, AModularWeaponBP_Mace_High_Tier_Short_C::StaticClass() },
        { 157, AModularWeaponBP_Mace_Low_Tier_Short_C::StaticClass() },
        { 158, AModularWeaponBP_Mace_Mid_Tier_Avg_C::StaticClass() },
        { 159, AModularWeaponBP_Mace_Mid_Tier_Short_C::StaticClass() },
        { 160, AModularWeaponBP_Polearm_High_Tier_C::StaticClass() },
        { 161, AModularWeaponBP_Polearm_Low_Tier_C::StaticClass() },
        { 162, AModularWeaponBP_Polearm_Mid_Tier_C::StaticClass() },
        { 163, AModularWeaponBP_Rondel_C::StaticClass() },
        { 164, AModularWeaponBP_Spear_A_C::StaticClass() },
        { 165, AModularWeaponBP_Spear_B_C::StaticClass() },
        { 166, AModularWeaponBP_WarStaff_A_C::StaticClass() },
        { 167, AModularWeaponBP_WarStaff_B_C::StaticClass() },
        { 168, AShield_BossGrip_C::StaticClass() },
        { 169, AShield_Buckler_C::StaticClass() },
        { 170, AShield_Pavise_Heavy_C::StaticClass() },
        { 171, AShield_Pavise_Light_C::StaticClass() },
        { 172, AShield_Pavise_Tower_C::StaticClass() },
        { 173, AShield_Tagre_C::StaticClass() },
    };

    inline AActor* SpawnActorFromClass(class UObject* WorldContextObject, TSubclassOf<class AActor> ActorClass, FTransform& SpawnTransform, AActor* Owner) {
        auto Spawned = UGameplayStatics::BeginDeferredActorSpawnFromClass(WorldContextObject,
            ActorClass,
            SpawnTransform,
            ESpawnActorCollisionHandlingMethod::AlwaysSpawn,
            Owner,
            ESpawnActorScaleMethod::SelectDefaultAtRuntime);

        return UGameplayStatics::FinishSpawningActor(Spawned, SpawnTransform, ESpawnActorScaleMethod::SelectDefaultAtRuntime);
    }

    inline void AskForItemAndSpawn(UWorld* World, AWillie_BP_C* CurrentPawn) {
        int ItemID;

        std::cout << "Enter Item ID (1-173): ";
        while (!(std::cin >> ItemID) || ItemMap.find(ItemID) == ItemMap.end()) {
            std::cin.clear();
            std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
            std::cout << "Invalid input. Please enter a valid Item ID (1-173): ";
        }

        SDK::FTransform CurrentPlayerTransform = CurrentPawn->GetTransform();
        CurrentPlayerTransform.Translation += CurrentPawn->GetActorForwardVector() * 40;
        SpawnActorFromClass(World, ItemMap.at(ItemID), CurrentPlayerTransform, nullptr);
    }
};