#include "ItemSpawner.h"
#include <iostream>

static const std::unordered_map<int, SDK::TSubclassOf<SDK::AActor>> ItemMap = {
        { 1, SDK::ABP_Armor_Arms_Chains_T1_C::StaticClass() },
        { 2, SDK::ABP_Armor_Arms_Chains_T2_C::StaticClass() },
        { 3, SDK::ABP_Armor_Arms_Vambrace_A_T2_C::StaticClass() },
        { 4, SDK::ABP_Armor_Arms_Vambrace_A_T3_C::StaticClass() },
        { 5, SDK::ABP_Armor_Arms_Vambrace_B_T2_C::StaticClass() },
        { 6, SDK::ABP_Armor_Arms_Vambrace_B_T3_C::StaticClass() },
        { 7, SDK::ABP_Armor_Arms_Vambrace_C_T2_C::StaticClass() },
        { 8, SDK::ABP_Armor_Arms_Vambrace_C_T3_B_C::StaticClass() },
        { 9, SDK::ABP_Armor_Arms_Vambrace_C_T3_C::StaticClass() },
        { 10, SDK::ABP_Armor_Body_Brestplate_A_T1_C::StaticClass() },
        { 11, SDK::ABP_Armor_Body_Brestplate_A_T2_C::StaticClass() },
        { 12, SDK::ABP_Armor_Body_Brestplate_B_T1_C::StaticClass() },
        { 13, SDK::ABP_Armor_Body_Brestplate_B_T2_C::StaticClass() },
        { 14, SDK::ABP_Armor_Body_Cuirass_A_T2_C::StaticClass() },
        { 15, SDK::ABP_Armor_Body_Cuirass_B_T1_C::StaticClass() },
        { 16, SDK::ABP_Armor_Body_Cuirass_C_T1_C::StaticClass() },
        { 17, SDK::ABP_Armor_Body_Cuirass_C_T2_C::StaticClass() },
        { 18, SDK::ABP_Armor_Body_Cuirass_C_T3_B_C::StaticClass() },
        { 19, SDK::ABP_Armor_Body_Cuirass_C_T3_C::StaticClass() },
        { 20, SDK::ABP_Armor_Body_Doublet_Arming_C::StaticClass() },
        { 21, SDK::ABP_Armor_Body_Doublet_C::StaticClass() },
        { 22, SDK::ABP_Armor_Body_Gambeson_A_T1_C::StaticClass() },
        { 23, SDK::ABP_Armor_Body_Gambeson_A_T2_C::StaticClass() },
        { 24, SDK::ABP_Armor_Body_Gambeson_B_T1_C::StaticClass() },
        { 25, SDK::ABP_Armor_Body_Gambeson_B_T2_C::StaticClass() },
        { 26, SDK::ABP_Armor_Body_Plackard_T2_C::StaticClass() },
        { 27, SDK::ABP_Armor_Body_Shirt_A_C::StaticClass() },
        { 28, SDK::ABP_Armor_Body_Shirt_B_C::StaticClass() },
        { 29, SDK::ABP_Armor_Feet_Sabbatons_AB_C::StaticClass() },
        { 30, SDK::ABP_Armor_Feet_Sabbatons_A_C::StaticClass() },
        { 31, SDK::ABP_Armor_Feet_Shoes_A_C::StaticClass() },
        { 32, SDK::ABP_Armor_Feet_Shoes_B_C::StaticClass() },
        { 33, SDK::ABP_Armor_Feet_Shoes_C_C::StaticClass() },
        { 34, SDK::ABP_Armor_Hands_Gauntlets_T1_C::StaticClass() },
        { 35, SDK::ABP_Armor_Hands_Gauntlets_T2_C::StaticClass() },
        { 36, SDK::ABP_Armor_Hands_Gauntlets_T3B_C::StaticClass() },
        { 37, SDK::ABP_Armor_Hands_Gauntlets_T3_C::StaticClass() },
        { 38, SDK::ABP_Armor_Hands_HalfGauntlets_T1_C::StaticClass() },
        { 39, SDK::ABP_Armor_Hands_HalfGauntlets_T2_C::StaticClass() },
        { 40, SDK::ABP_Armor_Head_Armet_001_B_C::StaticClass() },
        { 41, SDK::ABP_Armor_Head_Armet_001_C::StaticClass() },
        { 42, SDK::ABP_Armor_Head_Armet_001_R_C::StaticClass() },
        { 43, SDK::ABP_Armor_Head_Barbute_A_C::StaticClass() },
        { 44, SDK::ABP_Armor_Head_Barbute_B_C::StaticClass() },
        { 45, SDK::ABP_Armor_Head_Hat_Bycocket_A_001_C::StaticClass() },
        { 46, SDK::ABP_Armor_Head_Hat_Bycocket_A_002_C::StaticClass() },
        { 47, SDK::ABP_Armor_Head_Hat_Bycocket_B_001_C::StaticClass() },
        { 48, SDK::ABP_Armor_Head_Hat_Bycocket_B_002_C::StaticClass() },
        { 49, SDK::ABP_Armor_Head_Hat_Bycocket_C_001_C::StaticClass() },
        { 50, SDK::ABP_Armor_Head_Hat_Bycocket_D_001_C::StaticClass() },
        { 51, SDK::ABP_Armor_Head_Hat_Bycocket_E_001_C::StaticClass() },
        { 52, SDK::ABP_Armor_Head_Hat_Bycocket_F_001_C::StaticClass() },
        { 53, SDK::ABP_Armor_Head_Hat_Bycocket_G_001_C::StaticClass() },
        { 54, SDK::ABP_Armor_Head_Hat_Bycocket_H_001_C::StaticClass() },
        { 55, SDK::ABP_Armor_Head_Hat_Bycocket_I_001_C::StaticClass() },
        { 56, SDK::ABP_Armor_Head_Hat_Bycocket_J_001_C::StaticClass() },
        { 57, SDK::ABP_Armor_Head_Hat_Gnome_A_C::StaticClass() },
        { 58, SDK::ABP_Armor_Head_Hat_Gnome_B_C::StaticClass() },
        { 59, SDK::ABP_Armor_Head_Kettle_Helm_A_C::StaticClass() },
        { 60, SDK::ABP_Armor_Head_Kettle_Helm_B_C::StaticClass() },
        { 61, SDK::ABP_Armor_Head_Kettle_Helm_C_C::StaticClass() },
        { 62, SDK::ABP_Armor_Head_Kettle_Helm_D_C::StaticClass() },
        { 63, SDK::ABP_Armor_Head_Sallet_Open_A_001_C::StaticClass() },
        { 64, SDK::ABP_Armor_Head_Sallet_Open_B_001_C::StaticClass() },
        { 65, SDK::ABP_Armor_Head_Sallet_Open_CA_001_C::StaticClass() },
        { 66, SDK::ABP_Armor_Head_Sallet_Open_CB_001_C::StaticClass() },
        { 67, SDK::ABP_Armor_Head_Sallet_Solid_A_001_C::StaticClass() },
        { 68, SDK::ABP_Armor_Head_Sallet_Solid_A_002_C::StaticClass() },
        { 69, SDK::ABP_Armor_Head_Sallet_Solid_B_001_C::StaticClass() },
        { 70, SDK::ABP_Armor_Head_Sallet_Solid_B_002_C::StaticClass() },
        { 71, SDK::ABP_Armor_Head_Sallet_Solid_C_001_C::StaticClass() },
        { 72, SDK::ABP_Armor_Head_Sallet_Solid_C_002_C::StaticClass() },
        { 73, SDK::ABP_Armor_Head_Sallet_Solid_D_001_C::StaticClass() },
        { 74, SDK::ABP_Armor_Head_Sallet_Solid_D_002_C::StaticClass() },
        { 75, SDK::ABP_Armor_Head_Sallet_Solid_E_001_C::StaticClass() },
        { 76, SDK::ABP_Armor_Head_Sallet_Solid_E_002_C::StaticClass() },
        { 77, SDK::ABP_Armor_Head_Sallet_Visor_A_001_C::StaticClass() },
        { 78, SDK::ABP_Armor_Head_Sallet_Visor_B_001_C::StaticClass() },
        { 79, SDK::ABP_Armor_Legs_Cuisse_A_T2_C::StaticClass() },
        { 80, SDK::ABP_Armor_Legs_Cuisse_A_T3_C::StaticClass() },
        { 81, SDK::ABP_Armor_Legs_Cuisse_B_C::StaticClass() },
        { 82, SDK::ABP_Armor_Legs_Greaves_T2_C::StaticClass() },
        { 83, SDK::ABP_Armor_Legs_Greaves_T3_C::StaticClass() },
        { 84, SDK::ABP_Armor_Legs_Hosen_Arming_A_C::StaticClass() },
        { 85, SDK::ABP_Armor_Legs_Hosen_A_C::StaticClass() },
        { 86, SDK::ABP_Armor_Legs_Hosen_B_C::StaticClass() },
        { 87, SDK::ABP_Armor_Legs_Hosen_C_C::StaticClass() },
        { 88, SDK::ABP_Armor_Legs_Panties_C::StaticClass() },
        { 89, SDK::ABP_Armor_Neck_Bevor_T2_C::StaticClass() },
        { 90, SDK::ABP_Armor_Neck_Bevor_T3_C::StaticClass() },
        { 91, SDK::ABP_Armor_Neck_Standard_T1_C::StaticClass() },
        { 92, SDK::ABP_Armor_Neck_Standard_T2_C::StaticClass() },
        { 93, SDK::ABP_Armor_Neck_Standard_T3_C::StaticClass() },
        { 94, SDK::ABP_Armor_Shoulders_Pauldron_C_B_C::StaticClass() },
        { 95, SDK::ABP_Armor_Shoulders_Pauldron_C_C::StaticClass() },
        { 96, SDK::ABP_Armor_Shoulders_Spaulder_A_T2_C::StaticClass() },
        { 97, SDK::ABP_Armor_Shoulders_Spaulder_A_T3_C::StaticClass() },
        { 98, SDK::ABP_Armor_Shoulders_Spaulder_B_T2_C::StaticClass() },
        { 99, SDK::ABP_Armor_Shoulders_Spaulder_B_T3_C::StaticClass() },
        { 100, SDK::ABP_Armor_Waist_Foulds_T1_C::StaticClass() },
        { 101, SDK::ABP_Armor_Waist_Foulds_T2_C::StaticClass() },
        { 102, SDK::ABP_Armor_Waist_Foulds_T3_C::StaticClass() },
        { 103, SDK::ABP_Weapon_Improv_CandleStick_Big_C::StaticClass() },
        { 104, SDK::ABP_Weapon_Improv_CandleStick_Small_C::StaticClass() },
        { 105, SDK::ABP_Weapon_Improv_Stool_C::StaticClass() },
        { 106, SDK::ABP_Weapon_Tool_Axe_A_C::StaticClass() },
        { 107, SDK::ABP_Weapon_Tool_Axe_B_C::StaticClass() },
        { 108, SDK::ABP_Weapon_Tool_Axe_C_C::StaticClass() },
        { 109, SDK::ABP_Weapon_Tool_Hammer_A_C::StaticClass() },
        { 110, SDK::ABP_Weapon_Tool_Hammer_B_C::StaticClass() },
        { 111, SDK::ABP_Weapon_Tool_Hammer_C_C::StaticClass() },
        { 112, SDK::ABP_Weapon_Tool_Hoe_A_C::StaticClass() },
        { 113, SDK::ABP_Weapon_Tool_Knife_A_C::StaticClass() },
        { 114, SDK::ABP_Weapon_Tool_Knife_B_C::StaticClass() },
        { 115, SDK::ABP_Weapon_Tool_Knife_C_C::StaticClass() },
        { 116, SDK::ABP_Weapon_Tool_Pitchfork_A_C::StaticClass() },
        { 117, SDK::ABP_Weapon_Tool_Scissors_C::StaticClass() },
        { 118, SDK::ABP_Weapon_Tool_Shovel_A_C::StaticClass() },
        { 119, SDK::ABP_Weapon_Tool_Shovel_B_C::StaticClass() },
        { 120, SDK::ABP_Weapon_Tool_Sickle_A_C::StaticClass() },
        { 121, SDK::ABP_Weapon_Tool_Sickle_D_C::StaticClass() },
        { 122, SDK::ABP_Weapon_Tool_Sickle_E_C::StaticClass() },
        { 123, SDK::ABP_Weapon_Tool_Tongs_C::StaticClass() },
        { 124, SDK::AModularWeaponBP_ArmingSword_C::StaticClass() },
        { 125, SDK::AModularWeaponBP_ArmingSword_T1_C::StaticClass() },
        { 126, SDK::AModularWeaponBP_ArmingSword_T2_C::StaticClass() },
        { 127, SDK::AModularWeaponBP_ArmingSword_T3_C::StaticClass() },
        { 128, SDK::AModularWeaponBP_Axe2H_C::StaticClass() },
        { 129, SDK::AModularWeaponBP_Axe_C::StaticClass() },
        { 130, SDK::AModularWeaponBP_BastardSword_T1_C::StaticClass() },
        { 131, SDK::AModularWeaponBP_BastardSword_T2_C::StaticClass() },
        { 132, SDK::AModularWeaponBP_BastardSword_T3_C::StaticClass() },
        { 133, SDK::AModularWeaponBP_Billhook_A_C::StaticClass() },
        { 134, SDK::AModularWeaponBP_Billhook_B_C::StaticClass() },
        { 135, SDK::AModularWeaponBP_C::StaticClass() },
        { 136, SDK::AModularWeaponBP_Dagger_C::StaticClass() },
        { 137, SDK::AModularWeaponBP_Dagger_T1_C::StaticClass() },
        { 138, SDK::AModularWeaponBP_Dagger_T2_C::StaticClass() },
        { 139, SDK::AModularWeaponBP_Falchion_Long_C::StaticClass() },
        { 140, SDK::AModularWeaponBP_Falchion_Long_T1_C::StaticClass() },
        { 141, SDK::AModularWeaponBP_Falchion_Long_T2_C::StaticClass() },
        { 142, SDK::AModularWeaponBP_Falchion_Short_C::StaticClass() },
        { 143, SDK::AModularWeaponBP_Falchion_Short_T1_C::StaticClass() },
        { 144, SDK::AModularWeaponBP_Falchion_Short_T2_C::StaticClass() },
        { 145, SDK::AModularWeaponBP_GreatSword_C::StaticClass() },
        { 146, SDK::AModularWeaponBP_Hafted_High_Tier_Short_C::StaticClass() },
        { 147, SDK::AModularWeaponBP_Hafted_Low_Tier_Short_C::StaticClass() },
        { 148, SDK::AModularWeaponBP_Hafted_Mid_Tier_Avg_C::StaticClass() },
        { 149, SDK::AModularWeaponBP_Hafted_Mid_Tier_Long_C::StaticClass() },
        { 150, SDK::AModularWeaponBP_Hafted_Mid_Tier_Short_C::StaticClass() },
        { 151, SDK::AModularWeaponBP_Halberd_A_C::StaticClass() },
        { 152, SDK::AModularWeaponBP_Halberd_B_C::StaticClass() },
        { 153, SDK::AModularWeaponBP_LongSword_T2_C::StaticClass() },
        { 154, SDK::AModularWeaponBP_LongSword_T3_C::StaticClass() },
        { 155, SDK::AModularWeaponBP_Mace_High_Tier_Avg_C::StaticClass() },
        { 156, SDK::AModularWeaponBP_Mace_High_Tier_Short_C::StaticClass() },
        { 157, SDK::AModularWeaponBP_Mace_Low_Tier_Short_C::StaticClass() },
        { 158, SDK::AModularWeaponBP_Mace_Mid_Tier_Avg_C::StaticClass() },
        { 159, SDK::AModularWeaponBP_Mace_Mid_Tier_Short_C::StaticClass() },
        { 160, SDK::AModularWeaponBP_Polearm_High_Tier_C::StaticClass() },
        { 161, SDK::AModularWeaponBP_Polearm_Low_Tier_C::StaticClass() },
        { 162, SDK::AModularWeaponBP_Polearm_Mid_Tier_C::StaticClass() },
        { 163, SDK::AModularWeaponBP_Rondel_C::StaticClass() },
        { 164, SDK::AModularWeaponBP_Spear_A_C::StaticClass() },
        { 165, SDK::AModularWeaponBP_Spear_B_C::StaticClass() },
        { 166, SDK::AModularWeaponBP_WarStaff_A_C::StaticClass() },
        { 167, SDK::AModularWeaponBP_WarStaff_B_C::StaticClass() }
};

SDK::AActor* ItemSpawner::SpawnActorFromClass(class SDK::UObject* WorldContextObject,
    SDK::TSubclassOf<class SDK::AActor> ActorClass,
    struct SDK::FTransform& SpawnTransform,
    class SDK::AActor* Owner)
{
    auto Spawned = SDK::UGameplayStatics::BeginDeferredActorSpawnFromClass(WorldContextObject,
        ActorClass,
        SpawnTransform,
        SDK::ESpawnActorCollisionHandlingMethod::AlwaysSpawn,
        Owner,
        SDK::ESpawnActorScaleMethod::SelectDefaultAtRuntime);

    return SDK::UGameplayStatics::FinishSpawningActor(Spawned, SpawnTransform, SDK::ESpawnActorScaleMethod::SelectDefaultAtRuntime);
}

void ItemSpawner::AskForItemAndSpawn() {
    int ItemID;

    std::cout << "Enter Item ID (1-170): ";
    while (!(std::cin >> ItemID) || ItemMap.find(ItemID) == ItemMap.end()) {
        std::cin.clear();
        #undef max
        std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
        std::cout << "Invalid input. Please enter a valid Item ID (1-170): ";
    }

    SDK::UWorld* World = SDK::UWorld::GetWorld();
    SDK::APlayerController* PlayerController = World->OwningGameInstance->LocalPlayers[0]->PlayerController;
    class SDK::AWillie_BP_C* CurrentPawn = static_cast<SDK::AWillie_BP_C*>(PlayerController->Pawn);

    SDK::FTransform CurrentPlayerTransform = CurrentPawn->GetTransform();
    CurrentPlayerTransform.Translation += CurrentPawn->GetActorForwardVector() * 40;

    SpawnActorFromClass(World, ItemMap.at(ItemID), CurrentPlayerTransform, nullptr);
}